<?php
/**
 * STEMpunks Joomla Template
 *
 * @copyright   Copyright (C) Ben Klein
 * @license     GNU General Public License version 3 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

// Getting params from template
$params = JFactory::getApplication()->getTemplate(true)->params;

$app = JFactory::getApplication();
$doc = JFactory::getDocument();
$this->language = $doc->language;
$this->direction = $doc->direction;

// Detecting Active Variables
$option   = $app->input->getCmd('option', '');
$view     = $app->input->getCmd('view', '');
$layout   = $app->input->getCmd('layout', '');
$task     = $app->input->getCmd('task', '');
$itemid   = $app->input->getCmd('Itemid', '');
$sitename = $app->getCfg('sitename');

// Add current user information
$user = JFactory::getUser();

// Add JavaScript Frameworks
JHtml::_('jquery.framework');
JHtml::_('bootstrap.framework');
//$doc->addScript('templates/' .$this->template. '/js/jquery-1.9.1.min.js');
//$doc->addScript('templates/' .$this->template. '/js/bootstrap.min.js');

// Add Stylesheets
$doc->addStyleSheet('templates/'.$this->template.'/css/bootstrap.css');
$doc->addStyleSheet('templates/'.$this->template.'/css/stylish-portfolio.css');
$doc->addStyleSheet('templates/'.$this->template.'/css/responsive-video.css');
$doc->addStyleSheet('templates/'.$this->template.'/css/style.css');
$doc->addStyleSheet('templates/'.$this->template.'/css/homebg.css');
$doc->addStyleSheet('templates/'.$this->template.'/fa/css/font-awesome.min.css');

// Stuff that is loaded at bottom of page.
//$doc->addScript('templates/' .$this->template. '/js/grayscale.js');
//$doc->addScript('templates/' .$this->template. '/js/jquery.mixitup.min.js');
//$doc->addScript('templates/' .$this->template. '/js/jquery.easing.min.js');
//$doc->addScript('templates/' .$this->template. '/js/masonry.pkgd.min.js');
//$doc->addScript('templates/' .$this->template. '/js/imagesloaded.pkgd.min.js');
$doc->addScript('templates/' .$this->template. '/js/init.js');

?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="apple-touch-icon" sizes="196x196" href="templates/<?php echo $this->template;?>/images/apple-touch-icon.png" />
  <meta name="theme-color" content="#008000" />

  <!-- Head id autogenerated. -->
  <jdoc:include type="head" />

  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,%20700' rel="stylesheet" type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Oxygen:300,%20600' rel="stylesheet" type='text/css'>
  <script src="templates/<?php echo $this->template; ?>/js/bootstrap.min.js" type="text/javascript"></script>
  <!-- TODO Google analytics
  <script>
    (function(i, s, o, g, r, a, m) {
      i['GoogleAnalyticsObject'] = r;
      i[r] = i[r] || function() {
        (i[r].q = i[r].q || []).push(arguments)
      }, i[r].l = 1 * new Date();
      a = s.createElement(o), m = s.getElementsByTagName(o)[0];
      a.async = 1;
      a.src = g;
      m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
    ga('create', 'UA-47780525-1', 'lnstempunks.org');
    ga('send', 'pageview');
  </script> -->
</head>

<body class="blue">
  <div class="bg">
    <div id="carousel" class="carousel slide">
      <div class="carousel-inner">
      <?php if ($this->countModules('position-0')) : ?>
        <video poster="templates/<?php echo $this->template;?>/images/background1.jpg" id="bgvid" autoplay loop preload>
          <source src="http://lnstempunks.org/bg.webm" type="video/webm">
          <img id="bg">
        </video>
      <?php else : ?>
        <img id="bg">
      <?php endif ?>
      <script>
        var images = new Array('<?php echo $this->params->get('background1');?>',
                             '<?php echo $this->params->get('background2');?>',
                             '<?php echo $this->params->get('background3');?>');
        var l = images.length;
        var random_no = Math.floor(l*Math.random());document.getElementById("bg").src=images[random_no];
      </script>
      </div>
      <div class="gradient"></div>
    </div>
  </div>
  <div id="navbar" data-spy="affix" data-offset-top='20' class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-mobile">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<?php echo $this->baseurl; ?>">
          <img src="<?php echo $this->params->get('siteLogo');?>" height="50px">
        </a>
      </div>
      <div id="navbar-collapse-mobile" class="collapse navbar-collapse">
        <div id="navigation-items">
          <jdoc:include type="modules" name="navigation-items" style="none" />
        </div>
      </div>
    </div>
  </div>
  <header id="top" class="landing">
    <div class="text-vertical-center">
      <jdoc:include type="modules" name="position-0" style="none" />
    </div>
  </header>
  <div class="tab-content">
    <div class="tab-pane active slide-left in" id="landing_tab">
      <div id="services" class="section clear">
      </div>
      <div id="features" class="section">
        <div id="content">
          <?php if ($this->countModules('position-3')) : ?>
            <div class="container news">
              <jdoc:include type="modules" name="position-3" style="xhtml" />
            </div>
          <?php endif; ?>
          <!-- <div class="container newd gray"> -->
            <jdoc:include type="message" />
            <jdoc:include type="component" />
          <!-- </div> -->
          <?php if ($this->countModules('position-2')) : ?>
            <div class="container">
              <div class="arrow-down centered"></div>
              <jdoc:include type="modules" name="position-2" style="none" />
            </div>
          <?php endif; ?>
        </div>
      </div>
    </div>
  </div>

  <div class="section bottom clear">
    <div class="container clear">
      <div class="arrow-down centered"></div>
    </div>
  </div>
  <!-- TODO If no modules in any of these positions -->
  <div id="footer" class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-5 col-sm-5 col-xs-12">
          <div id="footer-bottom-left">
            <jdoc:include type="modules" name="footer-bottom-left" style="none" />
          </div>
        </div>
        <div class="col-md-1 col-sm-1 col-xs-0 empty"></div>
        <div class="col-md-3 col-sm-3 col-xs-6">
          <div id="footer-bottom-right">
            <jdoc:include type="modules" name="footer-bottom-right" style="none" />
          </div>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6">
          <div id="footer-bottom-far-right">
            <jdoc:include type="modules" name="footer-bottom-far-right" style="none" />
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- TODO Endif Footer Modules -->
</body>

</html>
