<?php
/**
 * STEMpunks Joomla Template
 *
 * @copyright   Copyright (C) Ben Klein
 * @license     GNU General Public License version 3 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

// Getting params from template
$params = JFactory::getApplication()->getTemplate(true)->params;

$app = JFactory::getApplication();
$doc = JFactory::getDocument();
$this->language = $doc->language;
$this->direction = $doc->direction;

// Detecting Active Variables
$option   = $app->input->getCmd('option', '');
$view     = $app->input->getCmd('view', '');
$layout   = $app->input->getCmd('layout', '');
$task     = $app->input->getCmd('task', '');
$itemid   = $app->input->getCmd('Itemid', '');
$sitename = $app->getCfg('sitename');

// Add Stylesheets
$doc->addStyleSheet('templates/'.$this->template.'/css/bootstrap.css');
$doc->addStyleSheet('templates/'.$this->template.'/css/stylish-portfolio.css');
$doc->addStyleSheet('templates/'.$this->template.'/css/responsive-video.css');
$doc->addStyleSheet('templates/'.$this->template.'/css/style.css');
$doc->addStyleSheet('templates/'.$this->template.'/css/homebg.css');
$doc->addStyleSheet('templates/'.$this->template.'/resources/fa/css/font-awesome.min.css');

// Add current user information
$user = JFactory::getUser();

// Add JavaScript Frameworks
JHtml::_('jquery.framework');
JHtml::_('bootstrap.framework');
//$doc->addScript('templates/' .$this->template. '/js/jquery.js');
//$doc->addScript('templates/' .$this->template. '/js/bootstrap.js');

// Stuff that is loaded at bottom of page.
$doc->addScript('templates/' .$this->template. '/js/js/grayscale.js');
$doc->addScript('templates/' .$this->template. '/js/js/masonry.pkgd.min.js');
$doc->addScript('templates/' .$this->template. '/js/js/imagesloaded.pkgd.min.js');
$doc->addScript('templates/' .$this->template. '/js/js/init.js');

?>

<!DOCTYPE html>
<html lang=en>

<head>
  <meta name=viewport content="width=device-width, initial-scale=1.0">
  <link rel=apple-touch-icon sizes=196x196 href="templates/<?php echo $this->template;?>/images/apple-touch-icon.png" />
  <meta name="theme-color" content="#008000">

  <!-- TODO Head id autogenerated. -->
  <jdoc:include type="head" />

  <meta name=author content="Sam Stair, Josh Witt, and Preston Gull">
  <meta name=description content="FIRST Robotics Competition team 3966 from downtown Knoxville, Tennessee.">.
  <meta name=keywords content="lnstempunks,3966,knoxvile,tennessee,knoxville tennessee,l&amp;nstempunks,stempunks,stem,punks,stem punks,l&amp;n,l&amp;n stempunks,l&amp;n steampunks,robotics,FIRST,FRC,VEX,robots,steampunk,steampunks,art,design,victorian,tnfirst,tn first,smoky mountains,smoky mountain,smoky mountain regional,smoky,mountain,regional,FIRST robotics competition,frc3966">
  <link rel=publisher href="https://plus.google.com/+LNSTEMpunksorg" />
  <link rel="shortcut icon" href="images/favicon.ico" />

  <title>Home - L&amp;N STEMpunks</title>

  <!-- CSS is loaded by Joomla
  <link href="css/bootstrap.css" rel=stylesheet>
  <link href="css/stylish-portfolio.css" rel=stylesheet>
  <link href="css/responsive-video.css" rel=stylesheet>
  <link href="css/style.css" rel=stylesheet>
  <link href="css/homebg.css" rel=stylesheet> -->
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,%20700' rel=stylesheet type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Oxygen:300,%20600' rel=stylesheet type='text/css'>
  <!-- TODO Library JS includes: may cause issues.
  <script src="js/jquery-1.9.1.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/jquery.mixitup.min.js"></script>
  <script src="js/jquery.easing.min.js"></script> -->
  <!-- TODO Google analytics
  <script>
    (function(i, s, o, g, r, a, m) {
      i['GoogleAnalyticsObject'] = r;
      i[r] = i[r] || function() {
        (i[r].q = i[r].q || []).push(arguments)
      }, i[r].l = 1 * new Date();
      a = s.createElement(o), m = s.getElementsByTagName(o)[0];
      a.async = 1;
      a.src = g;
      m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
    ga('create', 'UA-47780525-1', 'lnstempunks.org');
    ga('send', 'pageview');
  </script> -->
</head>
<!-- <script>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s);
    js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script> -->

<body class=blue>
  <div class=bg>
    <div id=carousel class="carousel slide">
      <div class=carousel-inner>
      <?php if ($this->countModules('position-0')) : ?>
        <video poster="images/background1.jpg" id="bgvid" autoplay loop preload>
          <source src=bg.webm type="video/webm">
          <source src=bg.mp4 type="video/mp4">
          <img id=bg>
        </video>
      <?php else : ?>
        <img id=bg>
      <?php endif ?>
      <script>
        var images=new Array('<?php echo $this->params->get('background1');?>',
                             '<?php echo $this->params->get('background2');?>',
                             '<?php echo $this->params->get('background3');?>');
        var l=images.length;
        var random_no=Math.floor(l*Math.random());document.getElementById("bg").src=images[random_no];
      </script>
      </div>
      <div class=gradient></div>
    </div>
  </div>
  <div id=navbar data-spy=affix data-offset-top=20 class="navbar navbar-inverse">
    <div class=container>
      <div class=navbar-header>
        <button type=button class=navbar-toggle data-toggle=collapse data-target=.navbar-collapse>
          <span class=icon-bar></span>
          <span class=icon-bar></span>
          <span class=icon-bar></span>
        </button>
        <a class=navbar-brand href=.>
          <img src="<?php echo $this->params->get('siteLogo');?>">
        </a>
      </div>
      <div class="collapse navbar-collapse">
        <!-- TODO html-only/navigation-items.html SECTION -->
        <!-- <script>
          jQuery(function() {
            jQuery("#navigation-items").load("html-only/navigation-items.html");
          });
        </script> -->
        <div id="navigation-items">
          <jdoc:include type="modules" name="navigation-items" style="none" />
        </div>
      </div>
    </div>
  </div>
  <header id=top class=landing>
    <div class=text-vertical-center>
      <!-- TODO html-only/splash-overlay.html SECTION -->
      <script>
        jQuery(function() {
          jQuery("#splash-overlay").load("html-only/splash-overlay.html");
        });
      </script>
      <div id="splash-overlay">
        <h1 style="color: #fff;">LOADING...</h1>
      </div>
    </div>
  </header>
  <div class=tab-content>
    <div class="tab-pane active slide-left in" id=landing_tab>
      <div id=services class="section clear">
      </div>
      <div id=features class=section>
        <!-- TODO html-only/content.html SECTION -->
        <script>
          jQuery(function() {
            jQuery("#content").load("html-only/content.html");
          });
        </script>
        <div id="content"></div>
      </div>
    </div>
  </div>
  <!-- TODO Footer Arrow to close content -->
  <div class="section bottom clear">
    <div class="container clear">
      <div class="arrow-down centered"></div>
    </div>
  </div>
  <!-- TODO If no modules in any of these positions -->
  <div id=footer class=section>
    <div class=container>
      <div class=row>
        <div class="col-md-5 col-sm-5 col-xs-12">
          <!-- TODO html-only/left-footer.html SECTION -->
          <script>
            jQuery(function() {
              jQuery("#footer-bottom-left").load("html-only/left-footer.html");
            });
          </script>
          <div id="footer-bottom-left"></div>
        </div>
        <div class="col-md-1 col-sm-1 col-xs-0 empty"></div>
        <div class="col-md-3 col-sm-3 col-xs-6">
          <!-- TODO html-only/right-footer.html SECTION -->
          <script>
            jQuery(function() {
              jQuery("#footer-bottom-right").load("html-only/right-footer.html");
            });
          </script>
          <div id="footer-bottom-right"></div>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6">
          <!-- TODO html-only/far-right-footer.html SECTION -->
          <script>
            jQuery(function() {
              jQuery("#footer-bottom-far-right").load("html-only/far-right-footer.html");
            });
          </script>
          <div id="footer-bottom-far-right"></div>
        </div>
        </div>
      </div>
    </div>
    <!-- TODO Endif Footer Modules -->
  </div>
  <script src="js/grayscale.js" async></script>
  <script src="js/masonry.pkgd.min.js" async></script>
  <script src="js/imagesloaded.pkgd.min.js" async></script>
  <script src="js/init.js" async></script>
  <script>
    var $buoop = {};
    $buoop.ol = window.onload;
    window.onload = function() {
      try {
        if ($buoop.ol) $buoop.ol();
      } catch (e) {}
      var e = document.createElement("script");
      e.setAttribute("type", "text/javascript");
      e.setAttribute("src", "//browser-update.org/update.js");
      document.body.appendChild(e);
    }
  </script>
  <script>
    var images = new Array('images/background1.jpg', 'images/background2.jpg', 'images/background3.jpg');
    var l = images.length;
    var random_no = Math.floor(l * Math.random());
    document.getElementById("bg").src = images[random_no];
  </script>
</body>

</html>
